TwitterCredentials:

    Consumer:
        consumer_key: 'your_consumer_key'
        consumer_secret: 'your_consumer_secret'
    
    Access:
        access_token: 'your_access_token'
        access_secret: 'your_access_secret'